language: scala
scala:
  - 2.13.1
services: postgresql
before_script:
  - psql -c 'create database http4s_api_test;' -U postgres
  - sbt flywayMigrate
script:
  - sbt clean coverage test coverageReport
after_success:
  - sbt coveralls
